# 로컬 환경
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  sql:
    init:
      platform: local
      mode: EMBEDDED

  session:
    store-type: JDBC

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

# JPA log
#logging:
#  level:
#    org.hibernate:
#      sql: debug
#      type.descriptor.sql.BasicBinder: TRACE