spring:
  output:
    ansi:
      enabled: always

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: none

# DB 설정
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PWD}

# session 설정
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PWD}

# logging
logging:
  level:
    org.owasp.validator: off

# security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - profile
              - email

          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
            scope:
              - name
              - email
              - profile_image

            client-name: NAVER
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response